; This is a settings export file for the Yoast SEO plugin by Yoast.com - https://yoast.com/wordpress/plugins/seo/

[wpseo]
ignore_blog_public_warning = 
ignore_meta_description_warning = 
ignore_page_comments = 
ignore_permalink = 
ms_defaults_set = 
theme_description_found = ""
theme_has_description = 
version = "2.3.4"
alexaverify = ""
company_logo = ""
company_name = ""
company_or_person = "person"
disableadvanced_meta = 
googleverify = ""
msverify = ""
person_name = "Agus Prawoto Hadi"
website_name = ""
alternate_website_name = ""
yandexverify = ""

[wpseo_permalinks]
cleanpermalinks = 
cleanpermalink-extravars = ""
cleanpermalink-googlecampaign = 
cleanpermalink-googlesitesearch = 
cleanreplytocom = 
cleanslugs = 1
hide-feedlinks = 
hide-rsdlink = 
hide-shortlink = 
hide-wlwmanifest = 
redirectattachment = 
stripcategorybase = 
trailingslash = 

[wpseo_titles]
title_test = 0
forcerewritetitle = 1
separator = "sc-pipe"
noodp = 1
noydir = 1
usemetakeywords = 1
title-home-wpseo = "%%sitename%% %%page%% %%sep%% %%sitedesc%%"
title-author-wpseo = "%%name%%, Author at %%sitename%% %%page%%"
title-archive-wpseo = "%%date%% %%page%% %%sep%% %%sitename%%"
title-search-wpseo = "Hasil Pencarian %%searchphrase%% %%page%% %%sep%% %%sitename%%"
title-404-wpseo = "Halaman tidak ditemukan %%sep%% %%sitename%%"
metadesc-home-wpseo = "%%sitedesc%%"
metadesc-author-wpseo = ""
metadesc-archive-wpseo = ""
metakey-home-wpseo = ""
metakey-author-wpseo = ""
noindex-subpages-wpseo = 
noindex-author-wpseo = 
noindex-archive-wpseo = 1
disable-author = 
disable-date = 
title-post = "%%title%% %%page%% %%sep%% %%sitename%%"
metadesc-post = "%%excerpt%%"
metakey-post = ""
noindex-post = 
showdate-post = 
hideeditbox-post = 1
title-page = "%%title%% %%page%% %%sep%% %%sitename%%"
metadesc-page = "%%excerpt%%"
metakey-page = ""
noindex-page = 
showdate-page = 
hideeditbox-page = 1
title-attachment = "%%title%% %%page%% %%sep%% %%sitename%%"
metadesc-attachment = "%%excerpt%%"
metakey-attachment = ""
noindex-attachment = 
showdate-attachment = 
hideeditbox-attachment = 1
title-tax-category = "%%term_title%% Archives %%page%% %%sep%% %%sitename%%"
metadesc-tax-category = ""
metakey-tax-category = ""
hideeditbox-tax-category = 
noindex-tax-category = 
title-tax-post_tag = "%%term_title%% Archives %%page%% %%sep%% %%sitename%%"
metadesc-tax-post_tag = ""
metakey-tax-post_tag = ""
hideeditbox-tax-post_tag = 
noindex-tax-post_tag = 
title-tax-post_format = "%%term_title%% Archives %%page%% %%sep%% %%sitename%%"
metadesc-tax-post_format = ""
metakey-tax-post_format = ""
hideeditbox-tax-post_format = 
noindex-tax-post_format = 1

[wpseo_social]
fb_admins[] = 
fbconnectkey = "d0dc436018a6d9d28442c1900f023f61"
facebook_site = "https://www.facebook.com/agus.p.hadi.9"
instagram_url = ""
linkedin_url = ""
myspace_url = ""
og_default_image = ""
og_frontpage_title = ""
og_frontpage_desc = ""
og_frontpage_image = ""
opengraph = 1
googleplus = 1
pinterest_url = ""
pinterestverify = ""
plus-publisher = "https://plus.google.com/101955110240094692203/about"
twitter = 1
twitter_site = ""
twitter_card_type = "summary"
youtube_url = ""
google_plus_url = ""
fbadminapp = 0

[wpseo_rss]
rssbefore = ""
rssafter = "The post %%POSTLINK%% appeared first on %%BLOGLINK%%."

[wpseo_internallinks]
breadcrumbs-404crumb = "Error 404: Halaman tidak ditemukan"
breadcrumbs-blog-remove = 
breadcrumbs-boldlast = 
breadcrumbs-archiveprefix = "Archives for"
breadcrumbs-enable = 1
breadcrumbs-home = "Home"
breadcrumbs-prefix = ""
breadcrumbs-searchprefix = "Hasil pencarian"
breadcrumbs-sep = "»"
post_types-post-maintax = "category"
post_types-newsman_ap-maintax = "category"

[wpseo_xml]
disable_author_sitemap = 1
disable_author_noposts = 1
enablexmlsitemap = 1
entries-per-page = 1000
excluded-posts = ""
user_role-administrator-not_in_sitemap = 
user_role-editor-not_in_sitemap = 
user_role-author-not_in_sitemap = 
user_role-contributor-not_in_sitemap = 
user_role-subscriber-not_in_sitemap = 
post_types-post-not_in_sitemap = 
post_types-page-not_in_sitemap = 
post_types-attachment-not_in_sitemap = 1
taxonomies-category-not_in_sitemap = 
taxonomies-post_tag-not_in_sitemap = 
taxonomies-post_format-not_in_sitemap = 1
xml_ping_yahoo = 
xml_ping_ask = 
